{
 "title": "Definitivo",
 "time": { "from": "now", "to": "now +24h" },
 "templating": {
  "list": [
   {
    "name": "estacion",
    "query": {
     "query": "import \"influxdata/influxdb/schema\" schema.tagValues(bucket: \"mixed_bucket\", tag: \"estacion\")"
    }
   },
   { "name": "mapaICA", "query": "None, See" }
  ]
 },
 "panels": [
  { "title": "detalles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "mapaICA" },
  {
   "title": "Calidad Del Aire",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mixed_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> last()\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estado_aire_meteo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ica\")\n  // Filtro estricto por una estación concreta:\n  |> filter(fn: (r) => r[\"estacion\"] =~ /^${estacion}$/)\n  // Obligatorio en visualizaciones de series temporales para no saturar el frontend:\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"ica_estacion\")"
    }
   ]
  },
  {
   "title": "temperature prediction",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 13, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"mixed_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estado_aire_meteo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"estacion\"] =~ /^${estacion}$/)\n  // Unificamos todas las series fragmentadas en una sola\n  |> group() \n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Viento",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mixed_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> last()\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estado_aire_meteo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"viento_velocidad\")\n  // Filtro estricto por una estación concreta:\n  |> filter(fn: (r) => r[\"estacion\"] =~ /^${estacion}$/)\n  // Obligatorio en visualizaciones de series temporales para no saturar el frontend:\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"ica_estacion\")"
    }
   ]
  },
  {
   "title": "Precipitaciones",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "L/m2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mixed_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> last()\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estado_aire_meteo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precipitacion\")\n  // Filtro estricto por una estación concreta:\n  |> filter(fn: (r) => r[\"estacion\"] =~ /^${estacion}$/)\n  // Obligatorio en visualizaciones de series temporales para no saturar el frontend:\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"ica_estacion\")"
    }
   ]
  },
  { "title": "Mapa Camaras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Mapa de camaras",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"mixed_bucket\")\n  |> range(start: -2h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"camaras_directo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latitud\" or r[\"_field\"] == \"longitud\" or r[\"_field\"] == \"url_foto\")\n  |> last()\n  |> pivot(rowKey:[\"nombre_camara\", \"concello\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group() // <--- ¡ESTE ES EL TRUCO MÁGICO! Une todo en una sola tabla para Grafana"
    }
   ]
  },
  { "title": "Mapa ICA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "geoMap",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"mixed_bucket\")\n  |> range(start: now(), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"estado_aire_meteo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latitud\" or r[\"_field\"] == \"longitud\" or r[\"_field\"] == \"ica\" or r[\"_field\"] == \"rating\")\n  // 1. Agrupamos ESTRICTAMENTE por estación y campo. Ignoramos cualquier otra etiqueta que rompa la serie.\n  |> group(columns: [\"estacion\", \"_field\"])\n  // 2. Cogemos el PRIMER valor (el más cercano a now) en lugar del último\n  |> first() \n  // 3. Desagrupamos todo meterlo en un único saco antes de pivotar\n  |> group()\n  // 4. Pivotamos usando SOLO la estación como identificador de fila\n  |> pivot(rowKey: [\"estacion\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  // 5. Limpiamos las columnas\n  |> keep(columns: [\"estacion\", \"latitud\", \"longitud\", \"ica\", \"rating\"])"
    }
   ]
  }
 ]
}