version: "3.8"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=somoslosmejores # ¡Cámbiala!
      - DOCKER_INFLUXDB_INIT_ORG=galicia_data
      - DOCKER_INFLUXDB_INIT_BUCKET=meteo_bucket
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - vaultwarden_web

  recolector_meteo:
    build: .
    container_name: recolector_meteo
    command: ["python", "-u", "recolector.py"]
    restart: unless-stopped
    networks:
      - vaultwarden_web

  recolector_ica:
    build: .
    container_name: recolector_ica
    command: ["python", "-u", "recolector_ica.py"]
    restart: unless-stopped
    networks:
      - vaultwarden_web

  recolector_aemet:
    build: .
    container_name: recolector_aemet
    command: ["python", "-u", "recolector_aemet.py"]
    restart: unless-stopped
    networks:
      - vaultwarden_web

  recolector_limpia_datos:
    build: .
    container_name: recolector_limpia_datos
    command: ["python", "-u", "recolector_limpia_datos.py"]
    restart: unless-stopped
    networks:
      - vaultwarden_web



  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - vaultwarden_web

  telegram_bot:
    build: ./botTelegramHackUdc
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=8736884501:AAH2e1BuT3FkKDTami4Cpjs7PGe-0HNl0_w
      - INFLUX_TOKEN=l4dwrX-J3b7KCJVl9naBD2YTz9VsvE2zAAqML-hXJw9CSuNHu118qPQVTyEIzJwy32RcZPyaQFtuWM9pNb44vw==
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./bot_data:/app/data  # Carpeta para SQLite
    networks:
      - vaultwarden_web
    depends_on:
      - ollama
      - influxdb
networks:
  vaultwarden_web:
    external: true
